services:
  - type: web
    name: quizzlee-app
    env: node
    buildCommand: npm ci && npm run build
    startCommand: npm run server
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    autoDeploy: true 