services:
  - type: web
    name: quizzlee-app
    env: node
    buildCommand: |
      echo "Forcing npm usage..."
      which npm
      npm --version
      echo "Installing dependencies..."
      npm install --legacy-peer-deps
      echo "Building application..."
      npm run build
      echo "Build completed!"
    startCommand: npm run server
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    autoDeploy: true 